Traceback (most recent call last):
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/flask/app.py", line 2069, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/flask/app.py", line 2054, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/server.py", line 9, in index
    mysql = connectToMySQL('first_flask')
  File "/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/mysqlconnection.py", line 43, in connectToMySQL
    return MySQLConnection(db)
  File "/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/mysqlconnection.py", line 6, in __init__
    connection = pymysql.connect(host = 'localhost',
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/pymysql/connections.py", line 921, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/pymysql/connections.py", line 959, in _process_auth
    return _auth.sha256_password_auth(self, auth_packet)
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/pymysql/_auth.py", line 186, in sha256_password_auth
    return _roundtrip(conn, data)
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/pymysql/_auth.py", line 120, in _roundtrip
    pkt = conn._read_packet()
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'rootroot'@'localhost' (using password: YES)")

Traceback (most recent call last):
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/flask/app.py", line 2069, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/flask/app.py", line 2054, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/server.py", line 9, in index
    mysql = connectToMySQL('first_flask')
  File "/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/mysqlconnection.py", line 43, in connectToMySQL
    return MySQLConnection(db)
  File "/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/mysqlconnection.py", line 6, in __init__
    connection = pymysql.connect(host = 'localhost',
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/pymysql/connections.py", line 921, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/pymysql/connections.py", line 959, in _process_auth
    return _auth.sha256_password_auth(self, auth_packet)
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/pymysql/_auth.py", line 182, in sha256_password_auth
    data = sha2_rsa_encrypt(conn.password, conn.salt, conn.server_public_key)
  File "/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/lib/python3.9/site-packages/pymysql/_auth.py", line 143, in sha2_rsa_encrypt
    raise RuntimeError(
RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
127.0.0.1 - - [12/May/2021 12:09:53] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [12/May/2021 12:09:53] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [12/May/2021 12:09:53] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [12/May/2021 12:09:53] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [12/May/2021 12:09:53] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
exit
^C%                                                                             (first_flask_mysql) noahbiggs@Noahs-MacBook-Pro first_flask_mysql % exit
Saving session...
...saving history...truncating history files...
...completed.
noahbiggs@Noahs-MacBook-Pro first_flask_mysql % pip install cryptography
zsh: command not found: pip
noahbiggs@Noahs-MacBook-Pro first_flask_mysql % pipenv shell
Launching subshell in virtual environment...
 . /Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/bin/activate
Restored session: Wed May 12 12:12:31 CDT 2021
noahbiggs@Noahs-MacBook-Pro first_flask_mysql %  . /Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/bin/activate


SyntaxError: invalid non-printable character U+00A0
(first_flask_mysql) noahbiggs@Noahs-MacBook-Pro first_flask_mysql % python server.py
Traceback (most recent call last):
  File "/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/server.py", line 2, in <module>
    from mysqlconnection import connectToMySQL
  File "/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/mysqlconnection.py", line 2, in <module>
    import pymysql.cursors
ModuleNotFoundError: No module named 'pymysql'
noahbiggs@Noahs-MacBook-Pro first_flask_mysql % pipenv shell
Launching subshell in virtual environment...
 . /Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/bin/activate
noahbiggs@Noahs-MacBook-Pro first_flask_mysql %  . /Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/bin/activate
(first_flask_mysql) noahbiggs@Noahs-MacBook-Pro first_flask_mysql % python filename.py
/Users/noahbiggs/.local/share/virtualenvs/first_flask_mysql-NEdcJQd6/bin/python: can't open file '/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/filename.py': [Errno 2] No such file or directory
(first_flask_mysql) noahbiggs@Noahs-MacBook-Pro first_flask_mysql % python server.py
Traceback (most recent call last):
  File "/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/server.py", line 2, in <module>
    from mysqlconnection import connectToMySQL
  File "/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/mysqlconnection.py", line 12
                                        autocommit = True)
    ^
SyntaxError: invalid non-printable character U+00A0
(first_flask_mysql) noahbiggs@Noahs-MacBook-Pro first_flask_mysql % python server.py
Traceback (most recent call last):
  File "/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/server.py", line 2, in <module>
    from mysqlconnection import connectToMySQL
  File "/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/mysqlconnection.py", line 12
                                        autocommit = True)
    ^
SyntaxError: invalid non-printable character U+00A0
(first_flask_mysql) noahbiggs@Noahs-MacBook-Pro first_flask_mysql % python server.py
Traceback (most recent call last):
  File "/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/server.py", line 2, in <module>
    from mysqlconnection import connectToMySQL
  File "/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/mysqlconnection.py", line 13
            # establish the connection to the database
    ^
SyntaxError: invalid non-printable character U+00A0
(first_flask_mysql) noahbiggs@Noahs-MacBook-Pro first_flask_mysql % python server.py
Traceback (most recent call last):
  File "/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/server.py", line 2, in <module>
    from mysqlconnection import connectToMySQL
  File "/Users/noahbiggs/Documents/CodingDojo/WebFund/PushToGitHub/python/Flask_mySQL/db_connection/first_flask_mysql/mysqlconnection.py", line 13
            # establish the connection to the database
    ^

